jingle:
  storage:
    host: ${HOST:127.0.0.1}
    database: ${DB_NAME:world}
    user: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
  ui:
    port: ${PORT:10909}
server:
  port: 5974

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      #自动更新
      ddl-auto: update
    show-sql: true
#  mvc:
#    favicon:
#      enabled: false
# 关闭查看actuator需要的验证
management:
  security:
    enabled: false