jingle:
  storage:
    host: ${HOST:127.0.0.1}
    database: ${DB_NAME:world}
    user: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
  ui:
    port: ${PORT:10909}
server:
  port: 10010

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
